// ------------------------------------------------------------------------------
//  <auto-generated>
//      此代码由编码的 UI 测试生成器生成。
//      版本: 14.0.0.0
//
//      如果重新生成代码，则更改此文件可能会导致错误的行为，
//      并将丢失这些更改。
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace AutoInputI.UIMaps.Convert1Classes
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public partial class Convert1
    {
        
        #region Properties
        public UI基金转换Window UI基金转换Window
        {
            get
            {
                if ((this.mUI基金转换Window == null))
                {
                    this.mUI基金转换Window = new UI基金转换Window();
                }
                return this.mUI基金转换Window;
            }
        }
        
        public UI柜台销售系统Window UI柜台销售系统Window
        {
            get
            {
                if ((this.mUI柜台销售系统Window == null))
                {
                    this.mUI柜台销售系统Window = new UI柜台销售系统Window();
                }
                return this.mUI柜台销售系统Window;
            }
        }
        
        public UI密码输入Window1 UI密码输入Window1
        {
            get
            {
                if ((this.mUI密码输入Window1 == null))
                {
                    this.mUI密码输入Window1 = new UI密码输入Window1();
                }
                return this.mUI密码输入Window1;
            }
        }
        
        public UI基金选择Window UI基金选择Window
        {
            get
            {
                if ((this.mUI基金选择Window == null))
                {
                    this.mUI基金选择Window = new UI基金选择Window();
                }
                return this.mUI基金选择Window;
            }
        }
        #endregion
        
        #region Fields
        private UI基金转换Window mUI基金转换Window;
        
        private UI柜台销售系统Window mUI柜台销售系统Window;
        
        private UI密码输入Window1 mUI密码输入Window1;
        
        private UI基金选择Window mUI基金选择Window;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI基金转换Window : WinWindow
    {
        
        public UI基金转换Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "基金转换";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TFrmConvert";
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        
        public UIItemWindow1 UIItemWindow1
        {
            get
            {
                if ((this.mUIItemWindow1 == null))
                {
                    this.mUIItemWindow1 = new UIItemWindow1(this);
                }
                return this.mUIItemWindow1;
            }
        }
        
        public UIItemWindow2 UIItemWindow2
        {
            get
            {
                if ((this.mUIItemWindow2 == null))
                {
                    this.mUIItemWindow2 = new UIItemWindow2(this);
                }
                return this.mUIItemWindow2;
            }
        }
        
        public UIItemWindow11 UIItemWindow11
        {
            get
            {
                if ((this.mUIItemWindow11 == null))
                {
                    this.mUIItemWindow11 = new UIItemWindow11(this);
                }
                return this.mUIItemWindow11;
            }
        }
        
        public UIItemWindow3 UIItemWindow3
        {
            get
            {
                if ((this.mUIItemWindow3 == null))
                {
                    this.mUIItemWindow3 = new UIItemWindow3(this);
                }
                return this.mUIItemWindow3;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        
        private UIItemWindow1 mUIItemWindow1;
        
        private UIItemWindow2 mUIItemWindow2;
        
        private UIItemWindow11 mUIItemWindow11;
        
        private UIItemWindow3 mUIItemWindow3;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "12";
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public UI基金转换Client UI基金转换Client
        {
            get
            {
                if ((this.mUI基金转换Client == null))
                {
                    this.mUI基金转换Client = new UI基金转换Client(this);
                }
                return this.mUI基金转换Client;
            }
        }
        #endregion
        
        #region Fields
        private UI基金转换Client mUI基金转换Client;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI基金转换Client : WinClient
    {
        
        public UI基金转换Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public WinButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WinButton(this);
                    #region 搜索条件
                    this.mUIItemButton.SearchProperties[WinButton.PropertyNames.ClassName] = "THsBitBtn";
                    this.SearchProperties[WinButton.PropertyNames.Instance] = "2";
                    this.mUIItemButton.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mUIItemButton.SearchConfigurations.Remove(SearchConfiguration.VisibleOnly);
                    this.mUIItemButton.WindowTitles.Add("基金转换");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WinButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WinButton(this);
                    #region 搜索条件
                    this.mUIItemButton1.SearchProperties[WinButton.PropertyNames.Name] = "...";
                    this.mUIItemButton1.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mUIItemButton1.SearchConfigurations.Remove(SearchConfiguration.VisibleOnly);
                    this.mUIItemButton1.WindowTitles.Add("基金转换");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIItemButton;
        
        private WinButton mUIItemButton1;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow1 : WinWindow
    {
        
        public UIItemWindow1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "THsEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("基金转换");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow2 : WinWindow
    {
        
        public UIItemWindow2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "THsEdit";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("基金转换");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow11 : WinWindow
    {
        
        public UIItemWindow11(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "THsComboBox";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "7";
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public WinComboBox UIItemComboBox
        {
            get
            {
                if ((this.mUIItemComboBox == null))
                {
                    this.mUIItemComboBox = new WinComboBox(this);
                    #region 搜索条件
                    this.mUIItemComboBox.WindowTitles.Add("基金转换");
                    #endregion
                }
                return this.mUIItemComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mUIItemComboBox;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow3 : WinWindow
    {
        
        public UIItemWindow3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public UI基金转换Client1 UI基金转换Client
        {
            get
            {
                if ((this.mUI基金转换Client == null))
                {
                    this.mUI基金转换Client = new UI基金转换Client1(this);
                }
                return this.mUI基金转换Client;
            }
        }
        #endregion
        
        #region Fields
        private UI基金转换Client1 mUI基金转换Client;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI基金转换Client1 : WinClient
    {
        
        public UI基金转换Client1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.WindowTitles.Add("基金转换");
            #endregion
        }
        
        #region Properties
        public WinButton UI关闭CButton
        {
            get
            {
                if ((this.mUI关闭CButton == null))
                {
                    this.mUI关闭CButton = new WinButton(this);
                    #region 搜索条件
                    this.mUI关闭CButton.SearchProperties[WinButton.PropertyNames.Name] = "关闭C";
                    this.mUI关闭CButton.WindowTitles.Add("基金转换");
                    #endregion
                }
                return this.mUI关闭CButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUI关闭CButton;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI柜台销售系统Window : WinWindow
    {
        
        public UI柜台销售系统Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "柜台销售系统";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TMainForm";
            this.WindowTitles.Add("柜台销售系统");
            #endregion
        }
        
        #region Properties
        public UIItemWindow4 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow4(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow4 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow4 : WinWindow
    {
        
        public UIItemWindow4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TTreeView";
            this.WindowTitles.Add("柜台销售系统");
            #endregion
        }
        
        #region Properties
        public UIItemTree UIItemTree
        {
            get
            {
                if ((this.mUIItemTree == null))
                {
                    this.mUIItemTree = new UIItemTree(this);
                }
                return this.mUIItemTree;
            }
        }
        #endregion
        
        #region Fields
        private UIItemTree mUIItemTree;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemTree : WinTree
    {
        
        public UIItemTree(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.WindowTitles.Add("柜台销售系统");
            #endregion
        }
        
        #region Properties
        public UI日常交易管理TreeItem UI日常交易管理TreeItem
        {
            get
            {
                if ((this.mUI日常交易管理TreeItem == null))
                {
                    this.mUI日常交易管理TreeItem = new UI日常交易管理TreeItem(this);
                }
                return this.mUI日常交易管理TreeItem;
            }
        }
        #endregion
        
        #region Fields
        private UI日常交易管理TreeItem mUI日常交易管理TreeItem;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI日常交易管理TreeItem : WinTreeItem
    {
        
        public UI日常交易管理TreeItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinTreeItem.PropertyNames.Name] = "日常交易管理";
            this.SearchProperties["Value"] = "0";
            this.WindowTitles.Add("柜台销售系统");
            #endregion
        }
        
        #region Properties
        public WinTreeItem UI基金转换TreeItem
        {
            get
            {
                if ((this.mUI基金转换TreeItem == null))
                {
                    this.mUI基金转换TreeItem = new WinTreeItem(this);
                    #region 搜索条件
                    this.mUI基金转换TreeItem.SearchProperties[WinTreeItem.PropertyNames.Name] = "基金转换";
                    this.mUI基金转换TreeItem.SearchProperties["Value"] = "1";
                    this.mUI基金转换TreeItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUI基金转换TreeItem.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUI基金转换TreeItem.WindowTitles.Add("柜台销售系统");
                    #endregion
                }
                return this.mUI基金转换TreeItem;
            }
        }
        #endregion
        
        #region Fields
        private WinTreeItem mUI基金转换TreeItem;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI密码输入Window1 : WinWindow
    {
        
        public UI密码输入Window1()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "密码输入";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPasswordInputForm";
            this.WindowTitles.Add("密码输入");
            #endregion
        }
        
        #region Properties
        public UIItemWindow5 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow5(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow5 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow5 : WinWindow
    {
        
        public UIItemWindow5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "THsEdit";
            this.WindowTitles.Add("密码输入");
            #endregion
        }
        
        #region Properties
        public WinEdit UIItemEdit
        {
            get
            {
                if ((this.mUIItemEdit == null))
                {
                    this.mUIItemEdit = new WinEdit(this);
                    #region 搜索条件
                    this.mUIItemEdit.WindowTitles.Add("密码输入");
                    #endregion
                }
                return this.mUIItemEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIItemEdit;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI基金选择Window : WinWindow
    {
        
        public UI基金选择Window()
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.Name] = "基金选择";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TFrmSelectFund";
            this.WindowTitles.Add("基金选择");
            #endregion
        }
        
        #region Properties
        public UIItemWindow6 UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow6(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow6 mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UIItemWindow6 : WinWindow
    {
        
        public UIItemWindow6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "TPanel";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("基金选择");
            #endregion
        }
        
        #region Properties
        public UI基金选择Client UI基金选择Client
        {
            get
            {
                if ((this.mUI基金选择Client == null))
                {
                    this.mUI基金选择Client = new UI基金选择Client(this);
                }
                return this.mUI基金选择Client;
            }
        }
        #endregion
        
        #region Fields
        private UI基金选择Client mUI基金选择Client;
        #endregion
    }
    
    [GeneratedCode("编码的 UI 测试生成器", "14.0.23107.0")]
    public class UI基金选择Client : WinClient
    {
        
        public UI基金选择Client(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region 搜索条件
            this.WindowTitles.Add("基金选择");
            #endregion
        }
        
        #region Properties
        public WinButton UI确定YButton
        {
            get
            {
                if ((this.mUI确定YButton == null))
                {
                    this.mUI确定YButton = new WinButton(this);
                    #region 搜索条件
                    this.mUI确定YButton.SearchProperties[WinButton.PropertyNames.Name] = "确定Y";
                    this.mUI确定YButton.WindowTitles.Add("基金选择");
                    #endregion
                }
                return this.mUI确定YButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUI确定YButton;
        #endregion
    }
}
